[package]
name = "homedo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.2", features = ["full"] }
axum = "0.8.6"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs"] }
